backend:
  name: github
  repo: kcompanyra-ux/Dash/
  branch: main
  base_url: https://auth.decapcms.org

collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "content.json"
        fields:
          - { label: "Browser Tab Title", name: "page_title", widget: "string" }
          - { label: "SEO Description", name: "page_description", widget: "text" }
          - { label: "Main Heading on Page", name: "main_heading", widget: "string" }
